version: "3.9"

volumes:
  data:

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    environment:
      - POSTGRES_DB=cyf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  myapp:
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres
